# Generated by Django 4.2.8 on 2023-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0002_rename_task_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2022-01-12'),
            preserve_default=False,
        ),
    ]
